import Foundation
@testable import PadelID

/// Anchor class used to find the unit-test bundle that carries the fixtures.
nonisolated final class FixtureBundleToken {}

nonisolated enum FixtureError: Error, CustomStringConvertible {
    case missing(String)

    var description: String {
        switch self {
        case .missing(let name): "Fixture \(name).json is not part of the test bundle"
        }
    }
}

/// Loads the API fixtures generated by `scripts/fixtures/export.sh` from the
/// real database code. XcodeGen copies them into the test bundle, either flat
/// or inside a `Fixtures` folder.
nonisolated enum FixtureLoader {
    static let allNames: [String] = [
        "me", "me_new", "home", "home_new", "matches_open", "matches_history", "match_action",
        "match_action_confirmed", "match_confirmed", "match_created", "player_profile", "player_matches",
        "rating_history", "dna", "search", "recent_players", "cities", "clubs", "preview", "username_check",
        "coach_application", "session", "signup", "new_user_session",
    ]

    static func url(_ name: String) -> URL? {
        let bundle = Bundle(for: FixtureBundleToken.self)
        return bundle.url(forResource: name, withExtension: "json", subdirectory: "Fixtures")
            ?? bundle.url(forResource: name, withExtension: "json")
    }

    static func data(_ name: String) throws -> Data {
        guard let url = url(name) else { throw FixtureError.missing(name) }
        return try Data(contentsOf: url)
    }

    static func decode<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
        try JSONCoding.decoder.decode(T.self, from: data(name))
    }
}
